### ISSUE TITLE
Errors when connecting with network down

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#473]
Emesene I left idle for about 10 minutes, and as I returned, I found several of these warnings.

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/iochannel.py", line 110, in <lambda>
    lambda chan, cond: self._post_open())
  File "/home/andre/emesene/emesene/e3/papylib/papyon/papyon/gnet/io/sock.py", line 54, in _post_open
    opts = self._transport.getsockopt(socket.SOL_SOCKET, socket.SO_ERROR)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor

**Comment by zipatei** [comment]
Try:
1. Network down
2. Emesene Reconnect automatic

Result: this warning

Another warning... Now is for clicking in "connect now":

Traceback (most recent call last):
  File "/home/andre/emesene/emesene/gui/gtkui/Login.py", line 833, in update_reconnect_timer
    service[0], service[1], on_reconnect=True)
  File "/home/andre/emesene/emesene/emesene.py", line 510, in on_login_connect
    self.window.content.clear_connect()
AttributeError: 'MainWindow' object has no attribute 'clear_connect'

**Comment by Mystro256** [comment]
Yeah, I've been getting random disconnects sometimes when idling on emesene with Ubuntu 11.04, I think it's related to this. Not sure though because it seems random for me :S

**Comment by c10ud** [comment]
i thought we fixed the connect now thing, are you using latest git?

**Comment by Mystro256** [comment]
hmmm, as I said it's random, I'm trying to get the terminal output to it but it seems difficult...

**Comment by zipatei** [comment]
Yes, i have latest git.

This errors, appear for connect now (2) and reconnecting automatic (1).

**Comment by c10ud** [comment]
was emesene completely broken after the first error? maybe that's "normal" when you try to connect with no network.. i could add a small check but it would be linux-specific and not so nice... (worse: networkmanager specific)

**Comment by zipatei** [comment]
No. Emesene it's fine after this errors.

This errors appear when emesene login. But network works at the moment.

**Comment by Sbte** [comment]
d36ed0bfb262a7d5515b537655471c9f2b16ac9e is the first bad commit
commit d36ed0bfb262a7d5515b537655471c9f2b16ac9e
Author: Riccardo (C10uD) c10ud.dev@gmail.com
Date:   Tue Apr 12 17:51:18 2011 +0200

```
Implement network detection in GNU/Linux through NetworkManager.

Thanks to UpdateManager sources. In particular to:
- Mohamed Amine IL Idrissi
- Canonical
- Alex Chiang
- Michael Vogt
i picked some code from various modules and created our nice NetworkManagerHelper.py
Happy disconnecting everyone.
```

:040000 040000 69db1a192594de881b77f01a7c91682ed59dc600 ce62624078b9cd5ee0149c0e84434d52b169bded M  emesene

@c10ud^

This causes on_reconnect to be called twice apparently. on_reconnect is called by on_disconnected, which is called by the signal signals.disconnected

**Comment by Sbte** [comment]
https://github.com/emesene/emesene/commit/d36ed0bfb262a7d5515b537655471c9f2b16ac9e#L0R136

I'm talking about this btw:

```
Traceback (most recent call last):
  File "/home/sven/emesene-dev/emesene/gui/gtkui/Login.py", line 833, in update_reconnect_timer
    service[0], service[1], on_reconnect=True)
  File "/home/sven/emesene-dev/emesene/emesene.py", line 494, in on_login_connect
    self.window.content.clear_connect()
AttributeError: 'Login' object has no attribute 'clear_connect'
```

**Comment by c10ud** [comment]
well, doesn't L136 look fine to you? it's just firing an event -- maybe i should just call the disconnect action instead? (more tested..?)

**Comment by Sbte** [comment]
It looks fine, but it's also called from papylib. So it's called twice, the functions are called twice, the reconnect timer is loaded twice, and one isn't unloaded. 

I guess it should only be called when someone is actually connected.

**Comment by Sbte** [comment]
Maybe disable it until someone is actually connected? It's only there to disconnect when there is no connection anymore right?
