### ISSUE TITLE
Move files from the main dir

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#1311]
Lately, a lot of files have been added to the main dir:

Info, Language, pygicompat, NotificationObject, WeakMethod, optionprovider, SingleInstance

Maybe we should fine a better place for those files? I don't really like having all those files there...

**Comment by jamesaxl** [comment]
we should keep only "emesene" but what sould we rename the directory ?

**Comment by Sbte** [comment]
I think most of it can be moved to our directory with random stuff: e3.common

**Comment by c10ud** [comment]
fine for me

**Comment by c10ud** [comment]
[11:21] <c10ud> $ ./emesene 
[11:21] <c10ud> Traceback (most recent call last):
[...]
[11:21] <c10ud>   File "emesene.py", line 224, in _parse_commandline
[11:21] <c10ud>     debugger.init(debuglevel=options.debuglevel)
[11:21] <c10ud> AttributeError: Values instance has no attribute 'debuglevel'
[11:26] <c10ud> $ git bisect good
[11:26] <c10ud> 41fb07de1d22b15d3141b890fd5ddf69d0b639b6 is the first bad commit
[11:26] <c10ud> commit 41fb07de1d22b15d3141b890fd5ddf69d0b639b6
[11:26] <c10ud> Author: Jose Rostagno joserostagno@vijona.com.ar
[11:26] <c10ud> Date:   Fri Jun 1 17:29:24 2012 -0300
[11:26] <c10ud>     Move file to e3.common Refs #1311
[11:26] <c10ud> :040000 040000 a91e7e724d3ea14d960059fa94b816fe7ae61e64 13fe1659dc549e4e5b9c9bb8f4c01e3f90532996 M emesene

**Comment by c10ud** [comment]
looks like it was registering only single instance

**Comment by c10ud** [comment]
Also: i don't think you can move Language because we need it in e3.base for i18n statuses

**Comment by c10ud** [comment]
Also: you cannot move NotificationObject because it's used by extension (which cannot be moved)

**Comment by Sbte** [comment]
Maybe we can make a separate folder for those (except for extension of course). This issue was meant for discussion mostly, not for moving stuff around at random :P

**Comment by c10ud** [comment]
since they're the "core" of emesene they would belong to e3...but they cannot be moved in there because of what i said above, i'd avoid creating yet-another-directory.. if you want you can try moving optionparser like pepe did (i think it can be moved, somehow) just pay attention that it works

**Comment by c10ud** [comment]
hello, i added a new file: CONTRIBUTORS, looks like this bug cannot be fixed
