### ISSUE TITLE
Group chat doesn't work

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#460]
```
[19:35:18 WARNING e3.common.Signal] Signal handler (on_new_conversation.on_new_conversation) error: 'NoneType' object has no attribute 'nick'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/emesene.py", line 613, in on_new_conversation
    conversation = conv_manager.new_conversation(cid, members)
  File "/home/sven/emesene/emesene/gui/base/ConversationManager.py", line 202, in new_conversation
    conversation = self.add_new_conversation(self.session, cid, members)
  File "/home/sven/emesene/emesene/gui/gtkui/ConversationManager.py", line 208, in add_new_conversation
    conversation = Conversation(self.session, cid, self.update_window, None, members)
  File "/home/sven/emesene/emesene/gui/gtkui/Conversation.py", line 144, in __init__
    self.output.clear(account, contact.nick, contact.display_name,
AttributeError: 'NoneType' object has no attribute 'nick'
[19:35:18 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 'NoneType' object has no attribute 'message_waiting'
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(*args, **kwargs) == False:
  File "/home/sven/emesene/emesene/e3/common/Signal.py", line 111, in __call__
    self.f(self.c(), *arg)
  File "/home/sven/emesene/emesene/e3/common/notification.py", line 109, in _on_message
    conversation.message_waiting:
AttributeError: 'NoneType' object has no attribute 'message_waiting'
```

Happens when someone else opens a group chat containing you.

**Comment by Sbte** [comment]
5baddf030312cfc90f22ba562f4e5d6c1737cb88 is the first bad commit
commit 5baddf030312cfc90f22ba562f4e5d6c1737cb88
Author: Jose Rostagno joserostagno@vijona.com.ar
Date:   Sun Apr 17 14:55:30 2011 -0300

```
Fix adium header and footer initialization
```

:040000 040000 b08ce6ae1fa9a14bb3964fb37a0314f15cc7bd7f 2630ecc87e0c364b54cc876ffb45bc5e2def66cf M  emesene

**Comment by c10ud** [comment]
if contact: same as now, else: clear()

**Comment by Sbte** [comment]
Fixed by bb8535bfba2479ede811

@pepeleproso, if you think there should be an else: self.output.clear(), please add it, I don't know what it does there in the first place. Also, please explain what it does. I want to know now :P
