### ISSUE TITLE
click buddy for chatting , an error occurred.

### ISSUE THREAD

**Issue by shwangdev** [emesene/emesene#1438]
Here is the log:

System : Ubuntu 12

Traceback (most recent call last):
  File "/home/xiangjianfeng/下载/linuxqq-emesene-4ad3f0f/emesene/gui/gtkui/ContactList.py", line 317, in _on_row_activated
    self.contact_selected.emit(contact)
  File "/home/xiangjianfeng/下载/linuxqq-emesene-4ad3f0f/emesene/e3/common/Signal.py", line 73, in emit
    (format_callback_name(callback), str(error)))
  File "/home/xiangjianfeng/下载/linuxqq-emesene-4ad3f0f/emesene/e3/common/Signal.py", line 82, in format_callback_name
    return func.f.__name__ + "." + func.f.**name**
AttributeError: 'weakref' object has no attribute '**name**'

**Comment by Sbte** [comment]
This is caused by 29fc3d95fa39bb258d8fd7613754e2f0e4eb9eb9 . It's because the function is a weakref too now. I'll see what I can do.
