### ISSUE TITLE
emesene is only 'gray' when connecting to MSN

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#635]
I was using emesene 1.6 in my ubuntu 10.10, and when I updated to 10.04 it updated too to emesene 2.
Now it doesn't connect.
After some seconds connecting to my MSN account the window goes empty, and it hangs there.
Here is the output from command line (running the latest release): http://pastebin.com/y4gqugUz

What should I do?
Not nice to have an unstable version shipped in a SO update to substitute a stable one :/

**Comment by pepeleproso** [comment]
I fixed this part of the log, in my theme refactoring:
  File "/opt/emesene/emesene/gui/gtkui/Window.py", line 45, in **init**
    self.gtk.window_set_default_icon(gui.theme.logo)
AttributeError: 'Window' object has no attribute 'gtk'

On the other side, the log show you have a badly packed emesene whitch lacks image theme.

**Comment by igorsantos07** [comment]
I tried using the default package from ubuntu repositories and the tarball
linked in the last blog post.
Should I try redownload it?
In time: it worked perfectly to connect to GTalk.

Igor Santos
   Programador Web

**Comment by pepeleproso** [comment]
try deleting emesene2 dir in ".config"

**Comment by c10ud** [comment]
install emesene from the stable ppa and it will work without issues

**Comment by igorsantos07** [comment]
Removing the old folder solved the problem (:
Now it's importing my emesene1 configs and everything looks nice now, thank
you (:

Igor Santos
   Programador Web
