### ISSUE TITLE
Not working in Windows 2.12.9?

### ISSUE THREAD

**Issue by juanraig** [emesene/emesene#1516]
Hello I have installed in windows 7 premium x64 but program cannot be installed after installation
Thanks for this new version (2.12.9)

**Comment by cquence** [comment]
Same here, Win7 Professional x64, after installation trying to run emesene does not start. Tried also to run as administrator with no effect. The application appears in the processes tab in Task Manager for a couple of seconds and then dies silently, no errors, no exceptions. Thanks for the new version!

**Comment by Sbte** [comment]
@pepeleproso

**Comment by moneycat** [comment]
I'm testing the portable version of 2.12.9 with debug mode. The error message shown in cmd is:

```
C:\Documents and Settings\moneycat>Z:\emesene\emesene_portable_debug.exe
No handlers could be found for logger "emesene.e3.common.DBus"
Traceback (most recent call last):
  File "emesene.py", line 111, in <module>
  File "e3\xmpp\__init__.pyo", line 1, in <module>
    栺
  File "e3\xmpp\Worker.pyo", line 38, in <module>

  File "sleekxmpp\__init__.pyo", line 9, in <module>

  File "sleekxmpp\basexmpp.pyo", line 37, in <module>
       
AttributeError: 'module' object has no attribute 'feature_starttls'
```

@Sbte @pepeleproso

**Comment by Sbte** [comment]
I don't get why that happens unless some file is not included in the package.

**Comment by pepeleproso** [comment]
I have no idea why those files are not included. I'll take a look but not before Thursday.

**Comment by pepeleproso** [comment]
please try this new installer https://github.com/downloads/emesene/emesene/emesene-2.12.9-20120913_2339-portable.exe

**Comment by juanraig** [comment]
Thanks has worked and started ok. Great Program. Cheers from Juan

**Comment by moneycat** [comment]
@juanraig Is there any related issues that you reopen this?

**Comment by pepeleproso** [comment]
thanks for testing this, I'll upload the non-portable version later today.

**Comment by juanraig** [comment]
Thanks friend.

2012/9/14 jose Rostagno notifications@github.com

**Comment by cquence** [comment]
Thanks for the fix. The portable version works OK now.
