### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'contact_list'

### ISSUE THREAD

**Issue by CelticHarp** [emesene/emesene#514]
Hello there. I have Debian squeeze, I used to have emesene 1.6, but now I decided to move on the latest emesene (2.11.4)
I tried it, it runs but when I type my msn account and try to log in, then nothing happens, the contact list shows nothing and it stops there.
So I tried to install emesene 2.0 from apt-get (with sid repositories) in order to have updated deps and finally my 2.11 to work (that was just a guess). But the result was the same. The 2.0 seems to work in the other hand, but not my 2.11.4!

I have:
Python 2.6.6 (r266:84292)
[GCC 4.4.5 20100824 (prerelease)] 

And my output is this:
amalia@home:~/Programs/emesene/emesene$ ./emesene
/usr/lib/python2.6/dist-packages/xmpp/auth.py:24: DeprecationWarning: the sha module is deprecated; use the hashlib module instead
  import sha,base64,random,dispatcher,re
/usr/lib/python2.6/dist-packages/xmpp/auth.py:26: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
18:45:04 WARNING e3.common.Signal] Signal handler (on_login_succeed.on_login_succeed) error: 'Session' object has no attribute 'get_profile'
Traceback (most recent call last):
  File "/home/amalia/Programs/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/amalia/Programs/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), _arg)
  File "/home/amalia/Programs/emesene/emesene/emesene.py", line 483, in on_login_succeed
    self.draw_main_screen()
  File "/home/amalia/Programs/emesene/emesene/emesene.py", line 424, in draw_main_screen
    self.on_new_conversation, self.on_close, self.on_user_disconnect)
  File "/home/amalia/Programs/emesene/emesene/gui/gtkui/Window.py", line 100, in go_main
    on_close, on_disconnect)
  File "/home/amalia/Programs/emesene/emesene/gui/gtkui/MainWindow.py", line 43, in **init**
    self.**hotmail = Hotmail(self.session)
  File "/home/amalia/Programs/emesene/emesene/e3/hotmail/Hotmail.py", line 46, in __init**
    self.profile = self.session.get_profile()
AttributeError: 'Session' object has no attribute 'get_profile'
[18:45:04 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "/home/amalia/Programs/emesene/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, **kwargs) == False:
  File "/home/amalia/Programs/emesene/emesene/e3/common/Signal.py", line 111, in **call**
    self.f(self.c(), *arg)
  File "/home/amalia/Programs/emesene/emesene/emesene.py", line 579, in on_contact_list_ready
    self.window.content.contact_list.fill()
AttributeError: 'NoneType' object has no attribute 'contact_list'

Any ideas? :)
Thanks in advance!!!

**Comment by c10ud** [comment]
do you have papyon>=0.5.5?

2011/5/5 CelticHarp
reply@reply.github.com:

**Comment by CelticHarp** [comment]
Oops, I forgot to mention it. Yes I do!

**Comment by CelticHarp** [comment]
Some more info about this package... don't know if it helps:

Package: python-papyon
Source: papyon
Version: 0.5.5-2
Provides: python2.6-papyon, python2.7-papyon
Depends: python2.6 | python2.7, python (>= 2.6.6-7~), python (<< 2.8), python-gobject (>= 2.10), python-openssl (>= 0.6), python-gst0.10, python-farsight, python-crypto
Filename: pool/main/p/papyon/python-papyon_0.5.5-2_all.deb

**Comment by c10ud** [comment]
can you try with latest git? https://github.com/emesene/emesene/tarball/master

2011/5/5 CelticHarp
reply@reply.github.com:

**Comment by CelticHarp** [comment]
Okay!! Problem solved now!! I found out some other issue too (I appear offline to my buddies) but I will research it first and then add a new issue if it isn't solved.
Thanks!!!!

**Comment by c10ud** [comment]
that's because you'll need the same papyon as ubuntus' natty-proposed
one, there's one critical fix in there

2011/5/5 CelticHarp
reply@reply.github.com:
